server:
  port: 8088

spring:
  application:
    name: health-check #项目名
  profiles:
    active: native
  datasource:
    #账号配置
    url: jdbc:mysql://127.0.0.1:3306/health-check?characterEncoding=utf8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

    #hikari数据库连接池
    hikari:
      pool-name: Retail_HikariCP
      minimum-idle: 20 #最小空闲连接数量
      idle-timeout: 180000 #空闲连接存活最大时间，默认600000（10分钟）
      maximum-pool-size: 200 #连接池最大连接数，默认是10
      auto-commit: true  #此属性控制从池返回的连接的默认自动提交行为,默认值：true
      max-lifetime: 1800000 #此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      connection-timeout: 30000 #数据库连接超时时间,默认30秒，即30000
      connection-test-query: SELECT 1

  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    initialize-schema: embedded
    properties:
      org:
        quartz:
          scheduler:
            instanceName: scheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 32
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

  mail:
    host: smtp.qq.com #\u53D1\u9001\u90AE\u4EF6\u670D\u52A1\u5668
    username: 406337039@qq.com #\u53D1\u9001\u90AE\u4EF6\u7684\u90AE\u7BB1\u5730\u5740
    password: zynoemarenqnbhjj #\u5BA2\u6237\u7AEF\u6388\u6743\u7801\uFF0C\u4E0D\u662F\u90AE\u7BB1\u5BC6\u7801\uFF0C\u8FD9\u4E2A\u5728qq\u90AE\u7BB1\u8BBE\u7F6E\u91CC\u9762\u81EA\u52A8\u751F\u6210\u7684
    properties.mail.smtp.port: 465 #\u7AEF\u53E3\u53F7465\u6216587
    from: 406337039@qq.com # \u53D1\u9001\u90AE\u4EF6\u7684\u5730\u5740\uFF0C\u548C\u4E0A\u9762username\u4E00\u81F4
    ## \u53EF\u4EE5\u4EFB\u610F
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
swagger:
  title: health-check
  description: health-check for swagger 2.x
  version: 1.0
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  termsOfServiceUrl:
  contact:
    name: ly
    url:
    email: 406337039@qq.com
  base-package: com.github.health.check
  base-path: /**

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
